---
title: "Buoy Map & Violin Plot by date"
author: "Yongrong Chai"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
#library(leaflet)
#library(viridis)
library(plotly)
#library(rworldmap)
#library(maps)
library(dplyr)
#library(ggmap)
library(readr)

```

```{r }
#https://www.ndbc.noaa.gov/measdes.shtml
#Wind speed -- WSPD
#Air temp -- ATMP
#41037 33.988 -77.362 --
#BFTN7 34.717 -76.671 --
#JMPN7 34.213 -77.786 --
#41110 34.142 -77.715 --
#41025 35.010 -75.454 --
#HCGN7 35.209 -75.704
#CLKN7 34.622 -76.525 --
#44056 36.200 -75.714 --
#"41037" "41110" "41025" "44056" "bftn7" "clkn7" "jmpn7" "hcgn7" 

#Meteorological factors were selected based on the map below with obvious fluctuation 
df1 <- mr41037 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "41037",lat = 33.988,lon = -77.362,
                                                     Code="NC",State="North Carolina")
df2 <- mr41110 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "41110",lat = 34.142,lon = -75.454)
#df3 <- mr41025 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "41025",lat = 35.010,lon = -77.715)
df4 <- mr44056 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "44056",lat = 36.200,lon = -75.714)
df5 <- mrbftn7 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "bftn7",lat = 34.717,lon = -76.671,
                                                     Code="NC",State="North Carolina")
df6 <- mrclkn7 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "clkn7",lat = 34.622,lon = -76.525,
                                                     Code="NC",State="North Carolina")
df7 <- mrjmpn7 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "jmpn7",lat = 34.213,lon = -77.786,
                                                     Code="NC",State="North Carolina")
df8 <- mrhcgn7 %>% select(DD, WSPD, ATMP, PRES) %>% mutate(buoy = "hcgn7",lat = 35.209,lon = -75.704,
                                                     Code="NC",State="North Carolina")
df.row <- bind_rows(df1,df2,df4,df5,df6,df7,df8)
df.row$WSPD <- as.numeric(df.row$WSPD)
df.row$ATMP <- as.numeric(df.row$ATMP)
df.row$TIDE <- as.numeric(df.row$TIDE)

by.map <- plyr::ddply(df.row,c("buoy", "DD"),numcolwise(mean)) #avg of each factor by date & buoy

fig1 <- plot_geo(by.map, locationmode = 'USA-states',frame = ~DD, lat = ~lat, lon = ~lon)%>%
       add_markers(sizes = c(50, 250),
             text = ~paste(WSPD, paste("buoy:",buoy), paste("lat:", lat), paste("lon:", lon), sep = "<br />"),
             color = ~buoy, size = ~WSPD, hoverinfo = "text") %>% 
       layout(title = 'Average Daily Wind Speed(m/s) in August 2011')


fig2 <- plot_geo(by.map, locationmode = 'USA-states',frame = ~DD, lat = ~lat, lon = ~lon)%>%
       add_markers(
             text = ~paste(ATMP, paste("buoy:",buoy), paste("lat:", lat), paste("lon:", lon), sep = "<br />"),
             color = ~buoy, size = ~ATMP, hoverinfo = "text") %>% 
       layout(title = 'Average Air Temperature(Celsius) in August 2011')
fig1
fig2
#APD, TIDE don't fluctuate much, so we don't select them
```

```{r }
#Based on the map above, we found that the index recorded by 41037 during the days of 26-28 influcated a lot
#WSPD Wind Speed(m/s)
vio41037 <- df.row %>%
  plot_ly(type = 'violin') %>%
  add_trace(
    x = ~DD[df.row$buoy == '41037'],
    y = ~WSPD[df.row$buoy == '41037'],
    legendgroup = '41037',
    scalegroup = '41037',
    name = '41037',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    ),
    color = I("blue")
  ) %>%
  layout(
    xaxis = list(
      title = "Days in August 2011"
    ),
    yaxis = list(
      title = "Wind Speed(m/s)",
      zeroline = F
    )
  )


#ATMP Air Temperature(Celsius)
vio41037.ATMP <- df.row %>%
  plot_ly(type = 'violin') %>%
  add_trace(
    x = ~DD[df.row$buoy == '41037'],
    y = ~ATMP[df.row$buoy == '41037'],
    legendgroup = '41037',
    scalegroup = '41037',
    name = '41037',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    ),
    color = I("blue")
  ) %>%
  layout(
    xaxis = list(
      title = "Days in August 2011"
    ),
    yaxis = list(
      title = "Air Temperature(Celsius)",
      zeroline = F
    )
  )

#PRES Sea level pressure (hPa)
vio41037.PRES <- df.row %>%
  plot_ly(type = 'violin') %>%
  add_trace(
    x = ~DD[df.row$buoy == '41037'],
    y = ~PRES[df.row$buoy == '41037'],
    legendgroup = '41037',
    scalegroup = '41037',
    name = '41037',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    ),
    color = I("blue")
  ) %>%
  layout(
    xaxis = list(
      title = "Days in August 2011"
    ),
    yaxis = list(
      title = "Sea level pressure (hPa)",
      zeroline = F
    )
  )


vio41037.WSPD
vio41037.ATMP
vio41037.PRES
```
