---
title: "wind time series for Irene&buoys"
author: "Clare Tang"
date: "2021/11/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(ggpubr)
library(hurricaneexposuredata)
library(hurricaneexposure)
```

## plots comparing wind speed from Irene and bouys

```{r, fig.width=8, fig.height=1.5}
data("hurr_tracks")
Irene_t <- hurr_tracks %>% filter(storm_id == "Irene-2011")
Irene_t$date <- ymd_hm(Irene_t$date)
wind_Irene <- Irene_t %>% ggplot(aes(x = date, y = wind/1.94384))+ # turn knot to m/s
  # geom_point()+
  scale_y_continuous(name="WSPD")+
  geom_line()+
  ggtitle("Wind change of Irene")+
  theme(plot.title = element_text(size = 25, face = "bold"))
wind_Irene

```


## Combined plots
```{r, fig.width=18, fig.height=8}

# Sys.setlocale("LC_ALL", "English")

# wind speed plot for five buoys
ggplot(data = all_buoys, mapping = aes(group = id, color = id, x = date_time, y = WSPD))+
  geom_line()+
  ggtitle("Wind speed of buoys")+
  theme(plot.title = element_text(size = 50, face = "bold"))+ 
  theme(legend.text=element_text(size=20))

```


```{r, fig.width=10, fig.height=8}
ts_bouys <- ggplot(data = all_buoys, mapping = aes(group = id, color = id, x = date_time, y = WSPD))+
  geom_line()+
  ggtitle("Wind speed of buoys")+
  theme(plot.title = element_text(size = 30, face = "bold"))+ 
  theme(legend.text=element_text(size=20))+
  facet_grid(id ~. )+
  theme(legend.position = "none")

ts_bouys

```
